SPACESHIP_TIME_SHOW=false

SPACESHIP_USER_SHOW=false

SPACESHIP_DIR_TRUNC=1 
SPACESHIP_DIR_TRUNC_REPO=true

# NodeJs
SPACESHIP_NODE_SYMBOL="🍀 "

#Dir
SPACESHIP_DIR_COLOR="magenta"
SPACESHIP_DIR_LOCK_SYMBOL="🔒"

#Separate line
SPACESHIP_PROMPT_SEPARATE_LINE=true

# Spaceship async
SPACESHIP_ASYNC_SHOW=false
SPACESHIP_ASYNC_SYMBOL=""

# Time exec
SPACESHIP_EXEC_TIME_SHOW=false

# Git
SPACESHIP_GIT_ASYNC=true
SPACESHIP_GIT_BRANCH_COLOR="yellow"

SPACESHIP_PACKAGE_SHOW=true
SPACESHIP_PACKAGE_SHOW_PRIVATE=true
SPACESHIP_PACKAGE_SYMBOL="📦 "
SPACESHIP_PACKAGE_COLOR="cyan"
