git:
  merging:
    args: "--no-ff"
gui:
  # hiển thị toàn bộ graph (tương đương git log --all --graph)
  showWholeGraph: true
customCommands:
  - key: "n"
    context: "localBranches"
    prompts:
      - type: "menu"
        title: "What kind of branch is it?"
        key: "BranchType"
        options:
          - name: "hotfix"
            description: "a hotfix branch"
            value: "hotfix"
          - name: "bug"
            description: "a bug branch"
            value: "bug"
          - name: "feature"
            description: "a feature branch"
            value: "feature"
          - name: "release"
            description: "a release branch"
            value: "release"
      - type: "input"
        title: "What is the new branch name?"
        key: "BranchName"
        initialValue: ""
    command: "git checkout -b {{.Form.BranchType}}/{{.Form.BranchName}}"
    loadingText: "Creating branch"
